# Generated by Django 4.1 on 2022-08-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0015_alter_productmodel_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='upload',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
