# Generated by Django 4.1 on 2022-08-23 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0017_cartmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cartmodel',
            name='price',
        ),
        migrations.AddField(
            model_name='cartmodel',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='demoapp.productmodel'),
            preserve_default=False,
        ),
    ]
